### PR TITLE
Issue 1: make default config directory if not exist

### LINKED ISSUE #1: .config/dbman/ must exist before default file is opened for creat
It would seem that the default config file can't be written unless the `/dbman` dir already exists.

For example - the first time I ran `dbman` the following was output...
`failed to create default config file: open /Users/jkmoore/.config/dbman/config.json: no such file or directory`

If I manually created the `.config/dbman` dir, all is well.
`default config file could not be found at '~/.config/dbman/config.json'; an empty config has been created with an example`

I'd be happy to tackle this if you desire.

### PR DESCRIPTION
**Pull request by Guitarbum722**
Resolves #1 

### Changes
- Create default config directory in `$HOME` if it doesn't already exist.
- Didn't change anything with the expectation that the config file is created if it doesn't exist.
- Renamed `filepath` parameter to `filePath` since the `path/filepath` package is now used (let me know if you want me to change the parameter name to something different).

### CODE REVIEW

File: config.go [hunk 1]
```diff
@@ -58,12 +58,17 @@ const (
...
-func LoadConfig(filepath string, isDefault bool, cfg *Config) error {
-	f, err := os.Open(filepath)
+func LoadConfig(filePath string, isDefault bool, cfg *Config) error {
+	f, err := os.Open(filePath)
 	if err != nil {
 		if os.IsNotExist(err) {
 			if isDefault {
-				f, err = os.Create(filepath)
+				dir := filepath.Dir(filePath)
+				if err := os.MkdirAll(dir, os.ModePerm); err != nil {
```
Comment (dabbertorres) [inline config.go]: `0755` is the more typical set of permissions for a user directory from my experience.

**Review by dabbertorres — CHANGES_REQUESTED** [review]
Looks good - thanks! The parameter name change is perfectly fine. Just have one comment.

File: config.go (hunk 1 above)
Comment (Guitarbum722) [reply config.go]: You got it.

**Review by dabbertorres — APPROVED** [review]

**Comment by dabbertorres** [comment]
Thanks!!
